import pandas as pd

# Define the 90-Day Plan Data
data = [
    # --- PHASE 1: FOUNDATIONS & DATA ENGINEERING (Days 1-30) ---
    (
        "Phase 1: Foundations",
        "Week 1",
        "Day 1",
        "Environment Setup",
        "Install VS Code, Git, Black, Pylance. Create GitHub Repo 'medical-ai-core'.",
        "Two Sum (HashMaps)",
        "Video: VS Code for Python Devs",
    ),
    (
        "Phase 1: Foundations",
        "Week 1",
        "Day 2",
        "Python OOP",
        "Refactor a script into a Class. Learn __init__, __str__ methods.",
        "Contains Duplicate (Sets)",
        "Article: Python Classes vs Functions",
    ),
    (
        "Phase 1: Foundations",
        "Week 1",
        "Day 3",
        "Data Formats",
        "Learn DICOM structure. Install pydicom & nibabel. Read 1 DICOM file.",
        "Valid Anagram (Freq Counter)",
        "Docs: Pydicom User Guide",
    ),
    (
        "Phase 1: Foundations",
        "Week 1",
        "Day 4",
        "Data Formats",
        "Learn NIfTI structure. Convert a DICOM series to 1 NIfTI volume.",
        "Maximum Subarray (Kadane)",
        "Video: DICOM vs NIfTI",
    ),
    (
        "Phase 1: Foundations",
        "Week 1",
        "Day 5",
        "Data Visualization",
        "Use matplotlib to visualize 3 slices (Axial, Coronal, Sagittal) of a 3D scan.",
        "Group Anagrams (HashMap)",
        "Library: matplotlib.pyplot",
    ),
    (
        "Phase 1: Foundations",
        "Week 1",
        "Day 6",
        "Weekly Review",
        "Push code to GitHub. Add a README. Review DSA.",
        "Review Week 1 Problems",
        "-",
    ),
    (
        "Phase 1: Foundations",
        "Week 1",
        "Day 7",
        "System Design Lite",
        "Sketch: How are CT scans stored in a hospital? (PACS servers).",
        "System Design Basics",
        "Video: Intro to PACS/DICOM",
    ),
    (
        "Phase 1: Foundations",
        "Week 2",
        "Day 8",
        "PyTorch Basics",
        "Tensors vs Arrays. GPU checking. Basic Tensor operations.",
        "Product of Array Except Self",
        "Docs: PyTorch Blitz",
    ),
    (
        "Phase 1: Foundations",
        "Week 2",
        "Day 9",
        "Custom Datasets",
        "Create 'MedicalVolumeDataset' class inheriting from torch.utils.data.Dataset.",
        "Top K Frequent Elements",
        "Tutorial: PyTorch Custom Datasets",
    ),
    (
        "Phase 1: Foundations",
        "Week 2",
        "Day 10",
        "Data Loading",
        "Implement __getitem__ to load NIfTI files on demand.",
        "Valid Sudoku",
        "-",
    ),
    (
        "Phase 1: Foundations",
        "Week 2",
        "Day 11",
        "Transforms",
        "Implement basic resizing and normalization (0-1 scaling).",
        "Longest Consecutive Sequence",
        "-",
    ),
    (
        "Phase 1: Foundations",
        "Week 2",
        "Day 12",
        "Dataloaders",
        "Use DataLoader to batch images. Test batch shapes.",
        "Valid Palindrome (2 Pointers)",
        "-",
    ),
    (
        "Phase 1: Foundations",
        "Week 2",
        "Day 13",
        "Review & Git",
        "Commit 'Data Loader' module. Refactor code.",
        "Review Week 2 Problems",
        "-",
    ),
    (
        "Phase 1: Foundations",
        "Week 2",
        "Day 14",
        "Math Refresh",
        "Understand Dice Loss vs Cross Entropy mathematically.",
        "3Sum",
        "Video: Loss Functions explained",
    ),
    (
        "Phase 1: Foundations",
        "Week 3",
        "Day 15",
        "Intro to MONAI",
        "Install MONAI. Run the 'Hello World' tutorial.",
        "Container With Most Water",
        "Docs: MONAI Core",
    ),
    (
        "Phase 1: Foundations",
        "Week 3",
        "Day 16",
        "MONAI Transforms",
        "Replace your manual transforms with MONAI (LoadImaged, Spacingd).",
        "Best Time to Buy/Sell Stock",
        "-",
    ),
    (
        "Phase 1: Foundations",
        "Week 3",
        "Day 17",
        "3D U-Net",
        "Import MONAI's BasicUNet. Print the model summary.",
        "Longest Substring Without Repeating",
        "Paper: U-Net Architecture",
    ),
    (
        "Phase 1: Foundations",
        "Week 3",
        "Day 18",
        "Training Loop",
        "Write the training loop (Optimizer, Loss, Backprop) for 3D data.",
        "Longest Repeating Char Replacement",
        "-",
    ),
    (
        "Phase 1: Foundations",
        "Week 3",
        "Day 19",
        "Validation Loop",
        "Implement Dice Metric for validation.",
        "Permutation in String",
        "-",
    ),
    (
        "Phase 1: Foundations",
        "Week 3",
        "Day 20",
        "Experiment Tracking",
        "Install TensorBoard/MLFlow. Log loss curves.",
        "Review Week 3",
        "-",
    ),
    (
        "Phase 1: Foundations",
        "Week 3",
        "Day 21",
        "Debug Model",
        "Overfit on a SINGLE image to check if model learns.",
        "Trapping Rain Water (Hard)",
        "-",
    ),
    (
        "Phase 1: Foundations",
        "Week 4",
        "Day 22",
        "Full Training",
        "Train on full Spleen Dataset (Medical Decathlon).",
        "Valid Parentheses (Stack)",
        "Dataset: MSD Spleen",
    ),
    (
        "Phase 1: Foundations",
        "Week 4",
        "Day 23",
        "Hyperparameters",
        "Tune Learning Rate and Batch Size.",
        "Min Stack",
        "-",
    ),
    (
        "Phase 1: Foundations",
        "Week 4",
        "Day 24",
        "Inference Script",
        "Write predict.py: Load model -> Predict -> Save Mask.",
        "Evaluate Reverse Polish Notation",
        "-",
    ),
    (
        "Phase 1: Foundations",
        "Week 4",
        "Day 25",
        "Visualization",
        "Overlay mask on original image and save as PNG.",
        "Generate Parentheses",
        "-",
    ),
    (
        "Phase 1: Foundations",
        "Week 4",
        "Day 26",
        "Code Cleanup",
        "Add docstrings. Make it look professional.",
        "Daily Temperatures",
        "-",
    ),
    (
        "Phase 1: Foundations",
        "Week 4",
        "Day 27",
        "GitHub Polish",
        "Write a professional README with screenshots.",
        "Review Week 4",
        "-",
    ),
    (
        "Phase 1: Foundations",
        "Week 4",
        "Day 28",
        "Buffer Day",
        "Catch up on pending tasks.",
        "Car Fleet",
        "-",
    ),
    (
        "Phase 1: Foundations",
        "Week 4",
        "Day 29",
        "Buffer Day",
        "Catch up on pending tasks.",
        "Largest Rectangle in Histogram",
        "-",
    ),
    (
        "Phase 1: Foundations",
        "Week 4",
        "Day 30",
        "PHASE 1 MILESTONE",
        "COMPLETE: Spleen Segmentation Pipeline.",
        "Review All Phase 1 DSA",
        "-",
    ),
    # --- PHASE 2: GEN AI, MLOPS & ADVANCED SKILLS (Days 31-60) ---
    (
        "Phase 2: GenAI & MLOps",
        "Week 5",
        "Day 31",
        "LLM Basics",
        "Understand Transformers, Tokens, Context Window.",
        "Binary Search",
        "Video: Andrej Karpathy LLM Intro",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 5",
        "Day 32",
        "Local LLMs",
        "Install Ollama. Run Llama-3 locally.",
        "Search a 2D Matrix",
        "Tool: Ollama",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 5",
        "Day 33",
        "RAG Concept",
        "Learn Retrieval Augmented Generation flow.",
        "Koko Eating Bananas",
        "Article: Pinecone RAG Guide",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 5",
        "Day 34",
        "Vector DBs",
        "Install ChromaDB. Create embeddings for a sample text.",
        "Find Minimum in Rotated Sorted Array",
        "-",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 5",
        "Day 35",
        "LangChain/LlamaIndex",
        "Connect LLM to Vector DB.",
        "Search in Rotated Sorted Array",
        "Docs: LangChain",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 5",
        "Day 36",
        "Medical RAG",
        "Ingest a PDF medical guideline into the DB.",
        "Time Based Key-Value Store",
        "-",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 5",
        "Day 37",
        "Chatbot UI",
        "Build a simple Streamlit UI for the RAG bot.",
        "Review Week 5",
        "Library: Streamlit",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 6",
        "Day 38",
        "Docker Intro",
        "Install Docker. Learn Image vs Container.",
        "Reverse Linked List",
        "Video: Docker for Beginners",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 6",
        "Day 39",
        "Dockerfile",
        "Write Dockerfile for your Spleen Segmentation app.",
        "Merge Two Sorted Lists",
        "-",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 6",
        "Day 40",
        "Docker Run",
        "Build and Run your container locally.",
        "Reorder List",
        "-",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 6",
        "Day 41",
        "FastAPI Basics",
        "Hello World API. Learn Pydantic models.",
        "Remove Nth Node From End of List",
        "Docs: FastAPI",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 6",
        "Day 42",
        "Inference API",
        "Create POST /predict endpoint for 3D Segmentation.",
        "Copy List with Random Pointer",
        "-",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 6",
        "Day 43",
        "Integration",
        "Test API with Postman/cURL.",
        "Add Two Numbers",
        "-",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 6",
        "Day 44",
        "Docker Compose",
        "Spin up API + Database using Compose.",
        "Linked List Cycle",
        "-",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 7",
        "Day 45",
        "AWS Setup",
        "Create Free Tier Account. Set up CLI.",
        "Find the Duplicate Number",
        "-",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 7",
        "Day 46",
        "ECR",
        "Push your Docker Image to AWS Elastic Container Registry.",
        "LRU Cache",
        "-",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 7",
        "Day 47",
        "EC2/Lambda",
        "Deploy the container on EC2 or Lambda.",
        "Invert Binary Tree",
        "-",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 7",
        "Day 48",
        "CI/CD Concepts",
        "What is GitHub Actions? Basic YAML config.",
        "Maximum Depth of Binary Tree",
        "-",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 7",
        "Day 49",
        "Auto-Test",
        "Write a PyTest case for your API.",
        "Diameter of Binary Tree",
        "-",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 7",
        "Day 50",
        "Review",
        "Ensure Cloud deployment works.",
        "Balanced Binary Tree",
        "-",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 7",
        "Day 51",
        "System Design",
        "Design: Scalable Medical Image Storage.",
        "Same Tree",
        "Ref: System Design Primer",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 8",
        "Day 52",
        "GenAI + Vision",
        "Intro to Vision Transformers (ViT).",
        "Subtree of Another Tree",
        "-",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 8",
        "Day 53",
        "Multimodal",
        "Concept: How to combine Image + Text (CLIP).",
        "Lowest Common Ancestor of BST",
        "-",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 8",
        "Day 54",
        "Project 2 Start",
        "Initialize 'Medical RAG Chatbot' Repo.",
        "Binary Tree Level Order Traversal",
        "-",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 8",
        "Day 55",
        "Project 2 Code",
        "Finalize RAG Pipeline.",
        "Binary Tree Right Side View",
        "-",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 8",
        "Day 56",
        "Project 2 API",
        "Wrap RAG in FastAPI.",
        "Count Good Nodes in Binary Tree",
        "-",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 8",
        "Day 57",
        "Project 2 UI",
        "Streamlit Frontend.",
        "Validate Binary Search Tree",
        "-",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 8",
        "Day 58",
        "Project 2 Done",
        "Document and Push to GitHub.",
        "Kth Smallest Element in a BST",
        "-",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 8",
        "Day 59",
        "Buffer",
        "Catch up.",
        "Construct Binary Tree from Preorder/Inorder",
        "-",
    ),
    (
        "Phase 2: GenAI & MLOps",
        "Week 8",
        "Day 60",
        "PHASE 2 MILESTONE",
        "COMPLETE: Cloud Deployed API & RAG Chatbot.",
        "Review All Phase 2 DSA",
        "-",
    ),
    # --- PHASE 3: INTERVIEW PREP & JOB HUNT (Days 61-90) ---
    (
        "Phase 3: Job Hunt",
        "Week 9",
        "Day 61",
        "Resume Rewrite",
        "Highlight: MONAI, Docker, RAG, AWS.",
        "Kth Largest Element in a Stream",
        "Action: Use 'STAR' method",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 9",
        "Day 62",
        "LinkedIn",
        "Update Headline. Post about your Project.",
        "Last Stone Weight",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 9",
        "Day 63",
        "Portfolio Site",
        "Create a simple GitHub Pages site linking your projects.",
        "K Closest Points to Origin",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 9",
        "Day 64",
        "Mock Interview 1",
        "Self-Record: 'Tell me about yourself'.",
        "Kth Largest Element in an Array",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 9",
        "Day 65",
        "System Design",
        "Design a Rate Limiter.",
        "Task Scheduler",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 9",
        "Day 66",
        "System Design",
        "Design Instagram (Photo Storage).",
        "Design Twitter",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 9",
        "Day 67",
        "Apply Tier 2",
        "Apply to 5 'Safe' companies.",
        "Review Heap/Priority Queue",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 10",
        "Day 68",
        "Graph Theory",
        "BFS/DFS Revision.",
        "Number of Islands",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 10",
        "Day 69",
        "Graph Algo",
        "Dijkstra's Algorithm.",
        "Max Area of Island",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 10",
        "Day 70",
        "Deep Learning Qs",
        "Prepare: 'Explain ResNet', 'Explain Attention'.",
        "Clone Graph",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 10",
        "Day 71",
        "Behavioral",
        "Prepare answers for conflict/challenges.",
        "Walls and Gates (or Rotting Oranges)",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 10",
        "Day 72",
        "Mock Interview 2",
        "Peer interview (Pramp or friend).",
        "Pacific Atlantic Water Flow",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 10",
        "Day 73",
        "Apply Tier 1",
        "Apply to Google, Microsoft, GE, Siemens.",
        "Surrounded Regions",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 10",
        "Day 74",
        "Review",
        "Analyze Rejections/Feedback.",
        "Review Graphs",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 11",
        "Day 75",
        "Adv DP",
        "Climbing Stairs / Cost (Easy DP).",
        "Climbing Stairs",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 11",
        "Day 76",
        "Adv DP",
        "House Robber.",
        "House Robber",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 11",
        "Day 77",
        "Adv DP",
        "Longest Palindromic Substring.",
        "Longest Palindromic Substring",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 11",
        "Day 78",
        "Network Qs",
        "HTTP vs HTTPS, REST vs gRPC.",
        "Palindromic Substrings",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 11",
        "Day 79",
        "SQL Basics",
        "Revise SELECT, JOIN, GROUP BY.",
        "Decode Ways",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 11",
        "Day 80",
        "Apply",
        "Apply to 5 more companies.",
        "Coin Change",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 11",
        "Day 81",
        "Buffer",
        "Catch up.",
        "Maximum Product Subarray",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 12",
        "Day 82",
        "Review All",
        "Full review of Resume/Projects.",
        "Word Break",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 12",
        "Day 83",
        "Final Polish",
        "Ensure GitHub repos are green (active).",
        "Longest Increasing Subsequence",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 12",
        "Day 84",
        "Mock Interview 3",
        "Full loop (Coding + System Design).",
        "Unique Paths",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 12",
        "Day 85",
        "Relax/Focus",
        "Focus on strongest skill.",
        "Longest Common Subsequence",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 12",
        "Day 86",
        "Apply Aggressive",
        "Cold Email Recruiters.",
        "Review DP",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 12",
        "Day 87",
        "Keep Learning",
        "Read a new paper (e.g., MedSAM).",
        "Insert Interval",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 12",
        "Day 88",
        "Keep Learning",
        "Read about Federated Learning.",
        "Merge Intervals",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 12",
        "Day 89",
        "Keep Learning",
        "Read about Explainable AI (SHAP).",
        "Non-overlapping Intervals",
        "-",
    ),
    (
        "Phase 3: Job Hunt",
        "Week 12",
        "Day 90",
        "GOAL",
        "You are now a Top 5% Candidate.",
        "Meeting Rooms II (or similar)",
        "-",
    ),
]

# Create DataFrame
df = pd.DataFrame(
    data,
    columns=[
        "Phase",
        "Week",
        "Day",
        "Focus Area",
        "Task (Technical)",
        "DSA Problem",
        "Resources/Notes",
    ],
)

# Save to Excel
file_name = "Medical_AI_90_Day_Plan.xlsx"
df.to_excel(file_name, index=False)

print(f"Success! '{file_name}' has been created with your 90-day plan.")
